### ISSUE TITLE
Why do errors trigger panic instead of just being returned?

### ISSUE THREAD

**Issue by jkirkwood** [BellerophonMobile/gonetworkmanager#9]
Hello. I'm interested in using your library, but my one hesitation is how much `panic()` is used throughout your code. I'm wondering why you panic vs. just returning the error to the function callers as is more typical for go libraries. I'm planning on using this lib as part of a larger program that handles many tasks, and I can't have the whole program crash if NetworkManager is down for some reason.

**Comment by tom5760** [comment]
The bulk of this library was written some time ago (May 2016), and since then we haven't been actively using it.  I've meant to do a number of improvements including returning errors (modules support, cleaner API, etc.), but haven't gotten around to it yet.

I'll try to find some time to improve things soon.  Otherwise, if you want to make any changes, feel free to make pull requests.

**Comment by jkirkwood** [comment]
Thanks for the quick response. I just found this fork of your project: https://github.com/Wifx/gonetworkmanager, and it seems to be pretty actively developed. It appears to have better error handing, and have a more complete API.

**Comment by tom5760** [comment]
I haven't seen that before, looks interesting.  I'll probably still try to refactor things here for now.  But seems like a good alternative.

**Comment by mullerch** [comment]
I've started the https://github.com/Wifx/gonetworkmanager recently and it's still a work in progress.
It targets NetworkManager 1.16 and has breaking changes.
I plan to do a pull request in the next few weeks, so if you have some time, please do not refactor the same things.

**Comment by tom5760** [comment]
Sure, thanks @mullerch!  

My general thoughts for refactorings are:
* Replace panics with error returns.
* The dbus interface strings probably shouldn't be public.  I think it just clutters the API.
* Just return structs instead of interfaces.
* Make all the struct constructors private, users get instances of them from the root `NetworkManager` type, or related methods instead.

**Comment by mullerch** [comment]
> * Replace panics with error returns.

I agree

> * The dbus interface strings probably shouldn't be public.  I think it just clutters the API.

I agree

> * Just return structs instead of interfaces.

Some types are polymorphic. E.g [Devices](https://github.com/BellerophonMobile/gonetworkmanager/blob/master/Device.go#L21).

If we want to use subtyping for Device.MarshallJSON() and Device.GetPath(), we should keep interfaces.

> * Make all the struct constructors private, users get instances of them from the root `NetworkManager` type, or related methods instead.

I currently use the constructors when I have the path of an object and want to access it. The `NetworkManager` type builds the structs only when he gets the path from the NetowrkManager (through a d-bus call). I think this should stay as it allows optimizations.

- Unify methods naming

I encountered some problems when implementing new methods on the `NetworkManager` type because properties and methods have identical sames. I deciced to standardize the properties accessors with `GetPropertyXXX` and `SetPropertyXXX` (instead of `GetXXX`). I think this should be unified over the whole API.

**Comment by jkirkwood** [comment]
@mullerch, @tom576 – Glad to see you guys sync up on this. I wanted to chime in on a couple things:

 @mullerch – in our email exchange you mentioned that you agreed method calls should return an error, but still planned on handling property call errors with `recover()`. I'm pretty new to Go as well, but it seems that `panic` is reserved for truly unrecoverable errors (see [here](https://golang.org/doc/effective_go.html#panic)). A property read failing because NM is down for a moment doesn't seem like a panic level event to me.

Regarding method names: going off of [this](https://golang.org/doc/effective_go.html#Getters), should property getters just be referred to by name (i.e. instead of `.GetState()`, just use `.State()`)? This would be both less verbose and more "Go-like". I don't think their are method/property conflicts for setters (I could me wrong), so maybe setters could simply remain `.SetXXX()`

Finally, would it make sense to create a new branch on this repo for this refactor? I think we all have a similar vision of where we want this library to go, and it might improve collaboration and visibility if we work together here.

**Comment by mullerch** [comment]
> in our email exchange you mentioned that you agreed method calls should return an error, but still planned on handling property call errors with recover()

It's not my final goal. It's just that I may not have the time to refactor everything. I think we all agree that errors should be handled by return for this API.

> I don't think their are method/property conflicts for setters (I could me wrong)

There is at least on case on the NetworkManager.

-  [NetworkManager.state](https://developer.gnome.org/NetworkManager/1.16/gdbus-org.freedesktop.NetworkManager.html#gdbus-method-org-freedesktop-NetworkManager.state) and [NetworkManager.State](https://developer.gnome.org/NetworkManager/1.16/gdbus-org.freedesktop.NetworkManager.html#gdbus-property-org-freedesktop-NetworkManager.State). We cannot discriminate by case in Go.
- [NetworkManager.GetDevices](https://developer.gnome.org/NetworkManager/1.16/gdbus-org.freedesktop.NetworkManager.html#gdbus-method-org-freedesktop-NetworkManager.GetDevices) and [NetworkManager.Devices](https://developer.gnome.org/NetworkManager/1.16/gdbus-org.freedesktop.NetworkManager.html#gdbus-property-org-freedesktop-NetworkManager.Devices). We cannot add just "Get" to the properties.

I agree for the new branch.

**Comment by jkirkwood** [comment]
Ok maybe it's best to stay with the `SetPropertyXXX/GetPropertyXXX` convention then.

I can work on refactoring the properties this week. Is it ok if I put together a pull request for this @mullerch?

**Comment by mullerch** [comment]
@jkirkwood of course. I'm waiting on @tom5760 for a branch on this repo to do a PR here, so I'll wait yours so that we can merge it all at the same time.

**Comment by tom5760** [comment]
Posted this in the PR comment thread, but repeating here:

At this point, I think it'd be better if @mullerch's repository was the primary repo for this library. I'm not actively using it for my work for a while, so it's hard to spend the time to give this the care it should have.

Would you be opposed to that? I can archive this repository, and update the README to point to yours.

**Comment by mullerch** [comment]
I'm not opposed, I'll keep working on this for a while so it sound good. I just merged the latest changes of this repo into ours.

**Comment by tom5760** [comment]
I've updated the README with a link to your fork.  I'm gonna archive this repo now to make sure it's clear.  Thanks for your work!  Feel free to mention me if anything changes.
